.prettierrc.js, i18n/en.pot, package.json, src/components/FormBase/index.js, src/components/Logger/index.js, src/components/Tree/__tests__/Tree.test.js, src/pages/import/helpers.js, yarn.lock
See https://jira.dhis2.org/browse/DHIS2-5853 comments for reasons for removing truncation. 
Not that there was a bug that made the client create the timestamp for summaries. This would make the timestamp be different from the server (like 1 hr after the other messages). I've removed the 'fake information' and replaced it with a timestamp, as according to Joe's comment. 
I decided to not remove the functionality of truncation, but added a flag for this. Mostly due the not knowing the reasons for doing this in the first place. I could've probably simplified it and removed the functionality all together, what do you think?
Also upgraded code-style and fixed the tests.
Sorry for upgrading code-style in a bug-fix, but it was the easiest way out, as the previous version staged all files.
=> fix(logger): remove logger truncation

config/webpack.config.dev.js, config/webpack.config.prod.js, package.json, src/App.js, src/components/FormBase/index.js, src/components/Loading/Progress.js, src/components/Loading/index.js, src/components/Loading/styles.css, src/helpers/xhr.js, yarn.lock
Adds a XHR-style upload indicator. Useful for bigger imports, so the user gets feedback of the progress. Note that the normal loading indicator is used for the server to process the data.
Needed to add some webpack-config to use the new UI, so the loaders include css from node-modules.
=> Upload indicator for imports

src/pages/export/MetaData.js
Added CSV for metadata, as the server now supports compression for csv as well. See https://jira.dhis2.org/browse/DHIS2-6162
Also added download=true parameter to set Content-Disposition header, so the nasty blob-hack is not needed for metadata-download.
Note that his hack is still in for metadata Dependency export and Data export. Need to bug backend team to fix this as well.
=> fix(metadata-export): add support for csv. Download directly from server

package.json, src/components/Form/Schemas/index.js, src/helpers/fields.js, src/helpers/values.js, src/pages/export/MetaData.js, src/reducers/index.js, src/reducers/schemas/actions.js, src/reducers/schemas/index.js, src/reducers/schemas/selectors.js, yarn.lock
See https://jira.dhis2.org/browse/DHIS2-5680.
When loading schemas, it preselected all schemas before filtering in metadata. Now also filters on the EXCLUDE_SCHEMAS list, as a workaround described in the ticket above. 
There seemed to be some performance problems with the schema-list - both with rendering and fetching unecessary. Ive now put the fetched list in the redux-store so it does not fetch each time an user visits the 'Metadata Export'-page.
Also moved 'checked' to be an Object instead of list, to improve rendering (so each item does not need to loop through the checked list - now just a O(1) operation).
=> fix(metadata export): filter selectable schemas on metadata and exclude schemas

src/components/Form/Schemas/index.js, src/components/Form/Schemas/index.test.js
Closes #38, closes #37
The schemas test was making actual network requests. Using the unconnected component with a shallow wrapper to prevent this.
=> fix: failing schemas test

src/helpers/fields.js, src/helpers/values.js, src/pages/import/MetaData.js
Fixes [DHIS2-6379](https://jira.dhis2.org/browse/DHIS2-6379)
Import mode is used in meta data import only, so simply renaming it should be safe.
I've moved it up to where the old "Dry run" previously was.
=> refactor(import meta data): rename import mode labels to dry run

i18n/en.pot, src/helpers/mime.js, src/helpers/xhr.js, src/pages/import/Data.js, src/pages/import/Event.js, src/pages/import/GML.js, src/pages/import/MetaData.js
This PR will change the way what Content-Type header is being sent with the request.
This will allow to send .zip files without having to have .json.zip as file extension.
Fixes DHIS2-6247 (https://jira.dhis2.org/browse/DHIS2-6247)
=> fix: use selected format instead of file extension for Content-Type header

src/components/FinalFormComponents/File.js, src/components/FinalFormComponents/__test__/__snapshots__/File.test.js.snap, src/components/Inputs/EventIdScheme.js, src/pages/import/Data.js, src/pages/import/Event.js, src/pages/import/Event/helper.js, src/pages/import/GML.js, src/pages/import/GML/helper.js, src/pages/import/MetaData.js, src/pages/import/helpers.js
Fixes DHIS2-7207
Implements the use of the new style already used on the metadata and data import pages also on the event and gml import pages.
It also
* fixes a bug introduced in v33 (DHIS2-7207)
* fixes a bug introduced by the final-form refactoring (clicking the file upload input triggers a submit)
(which is not a problem because the form can't be submitted until the file input has a value, but the required message is shown before the file dialog pops up)
Note: The refactoring so far only has been done on the way forms are implemented. The overall logic has not been refactored (yet). @ismay has made some comments in regards to what could/should be changed as well, we agreed on that being a topic for a different PR though
<hr />
Best way to check whether everything is still working is …
=> refactor(event & gml import pages): use final-form & new components

src/components/TaskSummary/helpers.js, src/components/TaskSummary/index.js, src/pages/import/helpers.js
When an event file is used with 0 event, currently no summary is shown as the shape of the response is not handled by the app.
This PR will introduce handling of that response shape and show an error to the user in the summary.
=>  fix: handle unknown api response shape

i18n/en.pot, src/components/TaskSummary/helpers.js, src/components/TaskSummary/index.js, src/pages/import/helpers.js
* fix(summary conflict): check length against 0 instead of array itself
This PR differs from the others because the v30 backend responded in a different way,
so I added the other scenario to the `fetchTaskSummary` function.
=>  fix: handle unknown api response shape (DHIS2-7207)

package.json, src/components/Form/index.js, src/components/FormBase/index.js, src/helpers/api.js, src/helpers/values.js, src/index.js, src/pages/export/Data.js, src/reducers/attributes/actions.js, src/reducers/attributes/index.js, src/reducers/attributes/thunks.js, src/reducers/index.js, src/store.js, yarn.lock
Preparing DHIS2-7495
* Dynamic options are now displayed on the export Data page
<hr />
Mentioning @Philip-Larsen-Donnelly so you stay up2date
=> feat(attributes): prepare attributes fetching & state management

i18n/en.pot, package.json, src/App.test.js, src/__mocks__/configureStore.js, src/components/Form/Radio/styles.css, src/components/Form/Schemas/__tests__/Schemas.test.js, src/components/Form/index.js, src/components/FormBase/index.js, src/configureStore.js, src/helpers/api.js, src/helpers/fields.js, src/helpers/values.js, src/index.js, src/pages/export/Data.js, src/pages/import/Data.js, src/reducers/attributes/__test__/selectors.test.js, src/reducers/attributes/__test__/thunks.test.js, src/reducers/attributes/actions.js, src/reducers/attributes/index.js, src/reducers/attributes/selectors.js, src/reducers/attributes/thunks.js, src/reducers/index.js, src/store.js, yarn.lock
Fixes DHIS2-6991 for v32
This is a backport for offering attribute options in the id scheme field when they're shared between data element id scheme and org unit id scheme (which means they have to be unique as well).
Seems to be working from my perspective (the only way to really test it for me is to check if the same/correct values are being sent).
I also had to modify the data import page which is different from v33/v34 as the later version already use RFF
=> Dynamic attribute options on Data ex- & import pages

package.json, src/pages/import/Data/helper.js, yarn.lock
Url-join joined the url wrong, so we're now concatenating the url manually.
Based on the changes in https://github.com/dhis2/import-export-app/pull/333, fixes https://jira.dhis2.org/browse/DHIS2-8082
=> fix(import-data-helper): join url manually

package.json, yarn.lock
Related to: https://jira.dhis2.org/browse/DHIS2-8082. Removing since it doesn't seem like it's used anymore.
=> chore(deps): remove unused url-join dependency

src/pages/import/MetaData/helper.js
This is a backport of #497. @vilkg approved backporting this during the hard freeze
=> fix: overwrite default error message only when a response message exists

.travis.yml
deploy-build uploads the `build` directory by default, but for App Platform apps it needs to upload `build/app` - see https://github.com/dhis2/data-visualizer-app/blob/master/.travis.yml#L14
=> chore(deploy): fix deploy-build to upload the correct directory

src/App.js
Forgot to import from `./locales`.
Addresses:
- DHIS2-9402 (Translations are not supported in import-export app)
=> fix(i18n): correctly import translations

src/components/JobSummary/Summary/Summary.js, src/components/JobSummary/Summary/Summary.module.css, src/components/JobSummary/__test__/__snapshots__/JobSummary.test.js.snap, src/components/JobSummary/__test__/__snapshots__/Summary.test.js.snap, src/utils/xhr.js
Fixes synchronous tracked entity instances import.
Also limit the max height of type report messages; apparently this can contain thousands of messages.
Synchronous tracked entity instances imports return a report inside the `response` property and not the `typeReports` property.
=> fix: sync tracked entity instance import

i18n/en.pot, src/components/Inputs/ExportButton.js, src/pages/DataExport/DataExport.js, src/pages/DataExport/form-helper.js, src/pages/EventExport/EventExport.js, src/pages/EventExport/form-helper.js, src/pages/MetadataDependencyExport/MetadataDependencyExport.js, src/pages/MetadataDependencyExport/form-helper.js, src/pages/MetadataExport/MetadataExport.js, src/pages/MetadataExport/form-helper.js, src/pages/TEIExport/TEIExport.js, src/pages/TEIExport/form-helper.js
When compression is selected we disable the export button for 5 seconds
reason: no way of knowing how long it actually takes the server to respond
Otherwise disable export button until server has responded.
Addresses:
- DHIS2-9488 (Export: missing user feedback when processing)
=> feat(export): disable export button while content is loading

i18n/en.pot, src/pages/DataExport/DataExport.js, src/pages/DataExport/form-helper.js, src/pages/EventExport/EventExport.js, src/pages/EventExport/form-helper.js, src/pages/MetadataDependencyExport/MetadataDependencyExport.js, src/pages/MetadataDependencyExport/form-helper.js, src/pages/MetadataExport/MetadataExport.js, src/pages/MetadataExport/form-helper.js, src/pages/TEIExport/TEIExport.js, src/pages/TEIExport/form-helper.js, src/utils/helper.js, yarn.lock
Disabling the export button for an arbitrary 5s regardless of how long it takes the server to respond doesn't really address the initial issue.
`locationAssign` now creates an iframe and leaves the export button disabled until the iframe has loaded which in our case also triggers a browser download prompt to appear.
The whole page also shows a circular loader while we're waiting for the server to respond.
Addresses:
- DHIS2-9488 (Export: missing user feedback when processing)
=> fix(export): show circular loader until download prompt appears

i18n/en.pot, src/pages/DataExport/form-helper.js, src/pages/TEIExport/TEIExport.js, src/pages/TEIExport/form-helper.js, src/utils/helper.js
The `dataValueSets` and `trackedEntityInstances` endpoints added support for the `attachment` parameter.
Client-side blob creation is now completely gone.
Addresses:
- DHIS2-9445 (Exported TEIs open in the browser, file is not downloaded)
See:
- DHIS2-9496 (Add download flag to dataValueSets and trackedEntityInstances)
- https://github.com/dhis2/dhis2-core/pull/6184
=> fix(data/tei-export): send attachment parameter

i18n/en.pot, src/components/Inputs/OrgUnitMode.js, src/components/Inputs/index.js, src/pages/TEIExport/TEIExport.js, src/pages/TEIExport/form-helper.js
Accessible, capture and ALL overrides the manual selection and the UI now reflects these overrides.
Addresses:
- DHIS2-9545 (Unclear if 'accessible' and 'capture' units overrride org.unit selection)
=> fix(tei-export/org-unit-mode): correctly show ouMode overrides

src/components/FormAlerts/FormAlerts.js
AlertBar used to cause CPU spikes up to a 100% of one core.
This change fixed it though I am not sure why.
=> fix: alert bar performance

i18n/en.pot, src/components/Inputs/AssignedUserMode.js, src/components/Inputs/AssignedUserModeFilter.js, src/components/Inputs/index.js, src/pages/DataExport/form-helper.js, src/pages/EventExport/form-helper.js, src/pages/MetadataDependencyExport/form-helper.js, src/pages/MetadataExport/form-helper.js, src/pages/TEIExport/TEIExport.js, src/pages/TEIExport/form-helper.js
Adds a new default option to `Assigned user mode` that disables filtering by `assignedUserMode`.
`assignedUserMode` set to `ANY` is not the same excluding the parameter completely from the parameters.
=> fix: tei export assigned user mode

src/components/Inputs/AssignedUserMode.js, src/pages/TEIExport/TEIExport.js, src/pages/TEIExport/form-helper.js
- only include the `assignedUser` parameter if `filter by assigned user` is selected
- aligns user picker with the rest of the related fields
=> fix(tei-export): only include `assignedUser` parameter if `filter by assigned user` is selected

i18n/en.pot, src/components/JobOverview/JobOverview.js, src/components/JobOverview/JobOverview.module.css, src/components/JobOverview/MenuLabel/MenuLabel.js, src/components/JobOverview/MenuLabel/MenuLabel.module.css, src/components/JobOverview/__test__/__snapshots__/JobOverview.test.js.snap, src/components/JobOverview/__test__/__snapshots__/MenuLabel.test.js.snap, src/components/JobSummary/JobSummary.js, src/components/JobSummary/Log/Log.js, src/components/JobSummary/SingleSummary/SingleSummary.js, src/components/JobSummary/Summary/Summary.js, src/components/JobSummary/TypeCount/TypeCount.js, src/components/JobSummary/TypeReportSummary/TypeReportSummary.js, src/components/JobSummary/__test__/JobSummary.test.js, src/components/JobSummary/__test__/Log.test.js, src/components/JobSummary/__test__/__snapshots__/JobSummary.test.js.snap, src/components/JobSummary/__test__/__snapshots__/Log.test.js.snap, src/components/JobSummary/__test__/__snapshots__/Summary.test.js.snap, src/components/JobSummary/__test__/__snapshots__/TypeCount.test.js.snap, src/components/JobSummary/__test__/__snapshots__/TypeReportSummary.test.js.snap, src/components/Page/__snapshots__/Page.test.js.snap, src/pages/JobOverview/JobOverview.js
- Changes title of main summary table from `Summary #Overview` to `Summary`
- Renames `Events` to `Log`
- Renames `Type count` to `Details by type`
- If user filters out the import job category of the selected job, the selected job is deselected and not shown on the page
These changes were discussed with Joe, Gintare and Phil.
---
Other improvements:
- Shows longer filenames on larger screens (truncate text with CSS)
- Single column layout on screens < 1200px (menu top, summary bottom)
=> fix: job overview wording and job selection

src/components/Geometry/GeometryPropertyMatch.js
This PR fixes an issue with the new GeoJSON importer where GeoJSON property name and the organisation unit id scheme is not included in the API url.
Fixes: https://dhis2.atlassian.net/browse/DHIS2-7171?focusedCommentId=175415
After this PR it is possible to match any GeoJSON property: 
Before it would show an error (because of fallback to feature id which is not present):
=> fix: geojson property name should match input field (DHIS2-7171)

i18n/en.pot, src/pages/EarthEngineImport/components/PopulationAgegroupsDataPreview.js, src/pages/EarthEngineImport/components/PopulationDataPreview.js
The text matches that of line-listing-app. Note that the ee importer has information about total rows and pages, so that is displayed in addition, unlike line-listing-app where this info is not available.
Line-listing app for reference:
This PR also includes a pot file entry from another PR where the pot file was forgotten.
=> fix: use convention for page summary text

i18n/en.pot, src/pages/EarthEngineImport/EarthEngineImportForm.js, src/pages/EarthEngineImport/components/DataPreview.js, src/pages/EarthEngineImport/components/MapGenderAgeGroupsTable.js, src/pages/EarthEngineImport/components/PopulationAgegroupsDataPreview.js, src/pages/EarthEngineImport/components/PopulationDataPreview.js
Keep rows per page in state.
https://user-images.githubusercontent.com/6113918/191472049-9a3180f5-cc6a-43fe-8ba8-b4f55876dc76.mov
=> fix: preserve users preferred rows per page for data preview [v39]

i18n/en.pot, src/pages/EarthEngineImport/EarthEngineImportForm.js, src/pages/EarthEngineImport/components/BandCocMappingTable.js, src/pages/EarthEngineImport/components/DataPreview.js, src/pages/EarthEngineImport/components/PopulationAgegroupsDataPreview.js, src/pages/EarthEngineImport/form-helper.js, src/pages/EarthEngineImport/util/earthEngines.js, src/pages/EarthEngineImport/util/getEarthEngineConfig.js, src/pages/EarthEngineImport/util/getStructuredData.js
Removed two //eslint-disable comments by refactoring the MappingTable component. 
I found that the `push` and `pop` from form.mutators don't seem to be memoized, as including them in the dependencies array was triggering the effect and causing bugs. Solution was to use form.change instead, which does seem to be memoized. This was also actually a cleaner solution as the effect now just sets the whole array of band-cocs to the array in the earthengine config (with props `id` and `name` instead of `bandId` and `bandName`).
Another refactor was to make the components agnostic as to which earth engine dataset is chosen. Instead of checking which dataset it is, the code checks whether the ee config has bands. This is a more flexible solution for when new ee datasets are added in the future.
=> fix: ee import - refactor to make sure all useEffect dependencies are listed [v39]

src/pages/EarthEngineImport/components/DataPreview.js, src/pages/EarthEngineImport/components/PopulationAgegroupsDataPreview.js, src/pages/EarthEngineImport/components/PopulationDataPreview.js
Do not persist the page number because it may become invalid when the preview is regenerated and there are fewer rows of data. Therefore, put the pageNo into the state for the components that are removed every time the preview is generated.
Side note: the two Population Preview components could probably be refactored since about 80% of the code is identical. But that will have to be done for a later version.
=> fix: page number needs to be reset to 1 when new preview generated [v39]

i18n/en.pot, package.json, patches/webpack+5.73.0.patch, yarn.lock
Fixes https://dhis2.atlassian.net/browse/DHIS2-13850
This patches webpack to fix a bug there causing issues with web workers. It’s not ideal as a generic webpack fix (which is why I haven’t yet opened a PR against webpack). We might want to instead update the publicPath in Create React App to use auto, solving it there instead of in webpack, though that requires more work to check all the edge cases.
However this should be very low-risk as a patch in the import/export app itself, because it only affects web workers and we only use web workers in this one place which has been tested thoroughly and works with the patch in place.
=> fix: patch webpack to support webworker importScripts with relative publicPath [v39]

package.json, patches/webpack+5.73.0.patch, yarn.lock
Fixes https://dhis2.atlassian.net/browse/DHIS2-13850
This uses [patch-package](https://www.npmjs.com/package/patch-package) to hot-fix webpack, adding support for "undoing" asset path to find the true root directory.  It's not an ideal solution, especially because some webpack tests are failing (perhaps they just need to be updated) but it does appear to solve the issue.
Another solution would be to patch the `webpack.config.js` config in `react-scripts` to use `publicPath: 'auto'`, but this requires further investigation to ensure it doesn't break i.e. the custom webpack plugins bundled with createReactApp.
=> fix: patch webpack to support webworker importScripts with relative publicPath

src/pages/EarthEngineImport/components/PopulationAgegroupsDataPreview.js
Fixes https://dhis2.atlassian.net/browse/DHIS2-13862
What was happening: there are competing scroll triggers - one for the main form that should scroll the entire form up to the top so user is shown the Job Summary, and the other for scrolling down to the data preview table when the user clicks the Preview button.
Before this fix, the effect for scrolling to the data preview was triggering when it shouldn't because bandCocs is never referentially equal, causing useMemo to trigger with every render. This then causes the data preview scroll to trigger after the Job Summary scroll.
=> fix: do not scroll to preview table during form submit

src/components/Inputs/ImportStrategy.js
This recreates PR https://github.com/dhis2/import-export-app/pull/1651
(we need to look into updating some of our CI workflows to make them runnable from external forks (see [DHIS2-14677](https://dhis2.atlassian.net/browse/DHIS2-14677)), hence the temporary need to recreate)
[DHIS2-14677]: https://dhis2.atlassian.net/browse/DHIS2-14677?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: use correct update strategy for metadata import [DHIS-12479]

src/components/Inputs/ImportStrategy.js
Hi Team, 
Raising this PR to fix the following bug 
https://dhis2.atlassian.net/browse/DHIS2-12479
The error is due to null pointer exception in the backend when strategy is "UPDATES". As per the backend logic, it is expecting "UPDATE" as strategy.  
Thanks,
Rithvik
=> fix: use correct metadata update strategy [DHIS-12479]  

src/pages/EarthEngineImport/components/EarthEngineId.js, src/pages/EarthEngineImport/util/earthEngineHelper.js, src/pages/EarthEngineImport/util/earthEngines.js
Related to: https://dhis2.atlassian.net/browse/DHIS2-14282
We now use the same Earth Engine dataset for both total population and age/gender groups. This ensures that the total population numbers are the same.
There is now only one period for Total population: 2020
=> fix: use same dataset for total population and age-group population

src/pages/EarthEngineImport/components/EarthEngineId.js, src/pages/EarthEngineImport/util/earthEngineHelper.js, src/pages/EarthEngineImport/util/earthEngines.js
Backport of https://github.com/dhis2/import-export-app/pull/1683
Related to: https://dhis2.atlassian.net/browse/DHIS2-14282
We now use the same Earth Engine dataset for both total population and age/gender groups. This ensures that the total population numbers are the same.
There is now only one period for Total population: 2020
=> fix: use same dataset for total population and age-group population [v39] (#1683)

src/components/DatePicker/DatePicker.js, src/components/DatePicker/DatePicker.test.js, src/components/DatePicker/DatePickerField.js, src/pages/DataExport/DataExport.js, src/pages/DataExport/form-helper.js, src/pages/EventExport/EventExport.js, src/pages/EventExport/form-helper.js, src/pages/TEIExport/form-helper.js
This fixes an issue with the DatePicker where if you are in a time zone earlier than UTC, the date you selected would be the previous day's date (i.e. I would try to select "2023-06-09" and I would get "2023-06-08"). See [DHIS2-12489](https://dhis2.atlassian.net/jira/software/c/projects/DHIS2/issues/DHIS2-12489).
Note: I guess we could update to our own calendar inputs and also fix the issue that way, but it seems maybe worth it to fix the bug first?
We have this bug because:
- we ultimately use a native <input type='date' />  element for our the date selector, which will store the selected date as a `yyyy-mm-dd` string (if it's implemented by the browser: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date)
- on change, we were converting the string value to a javascript …
=> fix: use string for date inputs [DHIS2-12489]

src/components/ElementSchemes/DataElementIdScheme.js, src/components/ElementSchemes/OrgUnitIdScheme.js, src/components/MoreOptions/MoreOptions.js, src/components/MoreOptions/MoreOptions.module.css, src/components/MoreOptions/__snapshots__/MoreOptions.test.js.snap, src/components/Page/__snapshots__/Page.test.js.snap
https://dhis2.atlassian.net/browse/DHIS2-16264
The select components do a fetch on render for attributes to populate some options (the top two or three are hard-coded though). If you select an option that was populated by the fetch, that value is saved in the Final Form state. If you collapse the Advanced Options section, then re-expand the section, the select tries to choose the option based on that value, _but_ the component needs to fetch again, so that option isn't available on first render
**Edited:**
I changed the `<MoreOptions>` component to keep children rendered to preserve state, and then hide them with CSS
Before:
https://github.com/dhis2/import-export-app/assets/49666798/6af20755-1c1d-4069-98f7-7ada89b0b83b
After:
https://github.com/dhis2/import-export-app/assets/49666798/50300 …
=> fix: avoid breaking selects [DHIS2-16264]

src/components/ElementSchemes/DataElementIdScheme.js, src/components/ElementSchemes/OrgUnitIdScheme.js, src/components/MoreOptions/MoreOptions.js, src/components/MoreOptions/MoreOptions.module.css, src/components/MoreOptions/__snapshots__/MoreOptions.test.js.snap, src/components/Page/__snapshots__/Page.test.js.snap
=> fix: avoid breaking selects (v39) [DHIS2-16264] (#1963)

.github/workflows/dhis2-verify-app.yml, d2.config.js, package.json
moving import/export app to continous release from v41. I didn't apply to earlier versions since it seems that a lot has changed between versions (geo import, and other stuff) so it's hard to tell what applies to all versions or not.
=> chore: move app to continuous release

i18n/en.pot, src/components/MergeOperation/MergeOperation.js, src/components/index.js, src/pages/MetadataImport/MetadataImport.js
Implements [DHIS2-16526](https://dhis2.atlassian.net/browse/DHIS2-16526)
------------------------
**Description**
This PR removes the Merge Mode options from the MetaData Import UI, i.e. choosing between `Merge` and `Replace`. It adds functionality to ensure that the merge option is always 'REPLACE'. It also notifies the user of this operation. 
------------------------
**Tasks**
------------------------
**Screenshots**
- Before:
- After:
[DHIS2-16526]: https://dhis2.atlassian.net/browse/DHIS2-16526?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(DHIS2-16526): remove merge mode from metadata import UI

i18n/en.pot, src/components/MergeOperation/MergeOperation.js, src/components/index.js, src/pages/MetadataImport/MetadataImport.js
**Description**
This PR removes the merge mode from the metadata import UI for v38 of the import-export app. 
**Reference issue** 
[DHIS2-16526](https://dhis2.atlassian.net/browse/DHIS2-16526)
**Related PR**
https://github.com/dhis2/import-export-app/pull/1986
[DHIS2-16526]: https://dhis2.atlassian.net/browse/DHIS2-16526?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: remove merge mode from metadata import UI

src/components/Inputs/FollowUpStatus.js, src/pages/EventExport/EventExport.js, src/pages/EventExport/form-helper.js, src/pages/TEIExport/TEIExport.js, src/pages/TEIExport/form-helper.js
This updates wrong parameters sent to the tracker API after feedback from the backend team:
- update the casing for `followup` params to `followUp`
- remove `skipPaging` param and use `paging=false` instead
- change the separator for arrays from [a semicolon to a comma](https://github.com/dhis2/dhis2-releases/blob/master/releases/2.41/README.md#semicolon-as-separator-for-identifiers-uid)
Relates to https://dhis2.atlassian.net/browse/DHIS2-16133
=> fix: update wrong parameters for tracker api migration

src/components/JobSummary/SingleSummary/SingleSummary.js, src/components/JobSummary/Summary/Summary.js
fixes [DHIS2-16133](https://dhis2.atlassian.net/browse/DHIS2-17046) - the "created" property was renamed from "imported" to "created". The UI was picking up the old property hence not displaying a value when there is one.
[DHIS2-16133]: https://dhis2.atlassian.net/browse/DHIS2-16133?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(tracker-api-migration): fix 'created' value not displaying in the job summary

src/components/Geometry/GeometryAttributePicker.js
Fixes https://dhis2.atlassian.net/browse/DHIS2-17071
The code will check if the "Import as associated geometry" is checked. If so, then the validator for that will run. Otherwise, it will not run the validator
=> fix(geojson-import): only run validator when the use geometry option is selected

src/components/Geometry/GeometryAttributePicker.js
Fixes https://dhis2.atlassian.net/browse/DHIS2-17071
Backport of https://github.com/dhis2/import-export-app/pull/2003
The code will check if the "Import as associated geometry" is checked.
If so, then the validator for that will run. Otherwise, it will not run the validator
=> fix(geojson-import): only run validator when the use geometry option is selected [v40]

src/components/Geometry/GeometryAttributePicker.js
Fixes https://dhis2.atlassian.net/browse/DHIS2-17071
Backport of https://github.com/dhis2/import-export-app/pull/2003
The code will check if the "Import as associated geometry" is checked. If so, then the validator for that will run. Otherwise, it will not run the validator
=> fix(geojson-import): only run validator when the use geometry option is selected [v39]

src/components/JobOverview/helper.js
Implements [DHIS2-17151](https://dhis2.atlassian.net/browse/DHIS2-17151)
---
Fix app crashing when Job summary is clicked while doing a Tracked entity Import as seen in this [link](https://www.loom.com/share/3ed7e03081bf49e0bc57e2477d032036?sid=c5c42ef0-b7bd-41ab-8f4d-c465c092e657) 
this is a backport from this [PR](https://github.com/dhis2/import-export-app/pull/2017)
---
-   [ ] None
---
[DHIS2-17151]: https://dhis2.atlassian.net/browse/DHIS2-17151?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: fix typeError that crashes app when job overview is clicked

src/utils/helper.js, src/utils/helper.test.js
This allows downloading exported `json` files - right now, it just opens in a new window since the API no longer returns the `content-disposition` header for JSON uncompressed. To fix that, we're using the [download](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#download) property of an anchor to trigger a download in the browser. Since the download is triggered programatically, rather than through a link element, we have to create the button in JS and trigger it, similar to this [solution](https://stackoverflow.com/a/49917066). 
Testing this solution needs to happen on the same origin, so it won't work on netlify. You need to build the app and install in an instance, then it works.  
fixes [DHIS2-16988](https://dhis2.atlassian.net/browse/DHIS2-16988)
[DHIS2-16988]: …
=> fix(DHIS2-16988): download uncompressed json rather than open inline

src/components/Inputs/ProgramPicker.js, src/components/Inputs/__tests__/ProgramPicker.test.js, src/components/ResourcePicker/ResourcePicker.js, src/components/ResourcePicker/queries.js, src/components/ResourcePicker/resourceTypes.js, src/pages/EventExport/EventExport.js
See https://dhis2.atlassian.net/jira/software/c/projects/DHIS2/issues/DHIS2-17672
This PR fixes an issue whereby the programs query had been amended to filter out WITHOUT_REGISTRATION (event) programs, which is relevant for the Tracked Entity Export page, but not for the Event export page.
Due to the structure of the existing code, I opted to just add an additional query (without filters) and look up the appropriate within <ProgramPicker> based on a new `includeEvents` parameter.
I've added a test for <ProgramPicker> to check that useDataQuery is called with the right query based on the `includeEvents` parameter. There is little test coverage in this app, currently; I think the test for this change could be written better, but it requires a bunch more setup, like setting up a query …
=> fix: include event programs for export [DHIS2-17672]

src/components/Inputs/ProgramPicker.js, src/components/Inputs/__tests__/ProgramPicker.test.js, src/components/ResourcePicker/ResourcePicker.js, src/components/ResourcePicker/queries.js, src/components/ResourcePicker/resourceTypes.js, src/pages/EventExport/EventExport.js
v39 backport of https://github.com/dhis2/import-export-app/pull/2058
tested against debug.dhis2.org/2.39dev
=> fix: include event programs for export [DHIS2-17672] (v39)
