- src/pages/import/Data.js
- src/pages/import/Event.js
- src/pages/import/GML.js
- src/pages/import/MetaData.js
- src/pages/import/helpers.js
fixes logging issues when imports are performed. MetadataAudit endpoint log has been removed
> Metadata import

- i18n/en.pot
- src/components/Form/File/index.js
- src/components/Form/File/styles.css
- src/components/Form/index.js
- src/components/FormBase/index.js
- src/helpers/__tests__/helpers.test.js
- src/helpers/fields.js
- src/helpers/form.js
- src/helpers/values.js
- src/helpers/xhr.js
- src/pages/export/Data.js
- src/pages/export/Event.js
- src/pages/export/MetaData.js
- src/pages/export/MetaDataDependency.js
- src/pages/import/Data.js
- src/pages/import/Event.js
- src/pages/import/GML.js
- src/pages/import/MetaData.js
Prevents importing without a file, causing a runtime-error and forever loading.
Also makes all the forms the same size, so they do not jitter around when switching sections.
> feat: add support for required fields and validation

- src/helpers/download.js
- src/helpers/index.js
- src/pages/export/MetaData.js
- src/pages/export/MetaDataDependency.js
Most of the code is refactoring for generating download URL. To clean up the OnSubmit functions.
> Dhis2 5292/skip sharing metadata dep export

- package.json
- src/components/Form/Schemas/__tests__/Schemas.test.js
- src/components/Form/Schemas/index.js
- src/helpers/values.js
- src/pages/export/MetaData.js
- src/reducers/index.js
- src/reducers/schemas/actions.js
- src/reducers/schemas/index.js
- src/reducers/schemas/selectors.js
- yarn.lock
* fix(metadata export): Filter selectable schemas on metadata and exclude schemas
* perf: use a set instead of array for EXCLUDE_SCHEMAS
* perf: cache schemas in redux-store, optimize rendering of schemas
* fix: update schemaParams to use object instead of array
* fix: fix failing test
> v31: fix(metadata export): filter selectable schemas on metadata and exclude schemas (#30)

- src/components/Form/Schemas/index.js
- src/helpers/values.js
- yarn.lock
Backport of #30 
Did not include the rework of schemas, as there was a lot of conflicts. This fixes the DHIS2-5680 bug though.
> fix(metadata export): filter selectable schemas on metadata and exclude schemas

- src/helpers/fields.js
- src/helpers/values.js
- src/pages/import/Data.js
- src/pages/import/MetaData.js
Fixes: [DHIS2-6061](https://jira.dhis2.org/browse/DHIS2-6061)
While adding the parameter I found the following bug which should be considered when reviewing this PR: [DHIS2-7221](https://jira.dhis2.org/browse/DHIS2-7221)
> feat: add firstRowIsHeader param for csv meta data import

- src/helpers/fields.js
- src/helpers/values.js
- src/pages/import/MetaData.js
Fixes [DHIS2-6379](https://jira.dhis2.org/browse/DHIS2-6379)
Backports #45
> refactor(import meta data): rename import mode labels to dry run

- src/components/FinalFormComponents/RadioGroup.js
- src/components/Inputs/SkipAudit.js
- src/components/WithAuthority.js
- src/pages/import/Data.js
> feat: add skip audit option to data import page

- src/helpers/form.js
- src/pages/import/Data/helper.js
I forgot to add the `skipAudit` value to the actual request.
Should be fixed with this PR
> fix(data import): add missing skip audit request parameter

- src/components/TaskSummary/helpers.js
- src/components/TaskSummary/index.js
- src/pages/import/helpers.js
* fix(summary conflict): check length against 0 instead of array itself
Backport for #62
> fix: handle unknown api response shape (DHIS2-7207)

- package.json
- src/components/Form/index.js
- src/components/FormBase/index.js
- src/helpers/api.js
- src/helpers/values.js
- src/index.js
- src/pages/export/Data.js
- src/reducers/attributes/actions.js
- src/reducers/attributes/index.js
- src/reducers/attributes/thunks.js
- src/reducers/index.js
- src/store.js
- yarn.lock
Prepares DHIS2-7495
Backports #67
> feat(attributes): prepare attributes fetching & state management

- src/components/FinalFormComponents/RadioGroup.js
- src/components/Inputs/DataElementIdScheme.js
- src/components/Inputs/OrgUnitIdScheme.js
- src/pages/export/Data.js
- src/pages/import/Data.js
- src/pages/import/Event.js
- src/reducers/attributes/actions.js
- src/reducers/attributes/index.js
- src/reducers/attributes/thunks.js
Fixes DHIS2-7495
Backports #68
> feat: add dynamic attributes to data & event import page (DHIS2-7495)

- cypress/integration/DataElementIdSchemeWithAttributes.feature
- cypress/integration/DataElementIdSchemeWithAttributes/index.js
- cypress/integration/IdSchemeWithCommonAttributes.feature
- cypress/integration/IdSchemeWithCommonAttributes/index.js
- cypress/integration/OrgUnitIdSchemeWithAttributes.feature
- cypress/integration/OrgUnitIdSchemeWithAttributes/index.js
Add missing "unique" keyword to the feature files ([requested here](https://jira.dhis2.org/browse/DHIS2-7495?focusedCommentId=29892&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-29892)).
> chore(features): add missing "unique" description

- cypress/integration/EndpointParamChecks/ExportMetaData/index.js
- src/components/Schemas/Schemas.js
> feat: optimize api schema request

- src/App.js
Following @Mohammer5 suggestion on return statement logic and putting `App.js` in line with the rest of the code base.
> chore: conditional rendering return statement simplified

- cypress/integration/EndpointParamChecks/ExportEvent.feature
- cypress/integration/EndpointParamChecks/ImportEvent.feature
- src/pages/EventExport/EventExport.js
- src/pages/EventExport/form-helper.js
- src/pages/EventImport/EventImport.js
- src/pages/EventImport/form-helper.js
Event import:
- Add id scheme selection input
Event export:
- Add data element scheme selection input
- Add org unit scheme selection input
relevant Jira issue: DHIS2-8714
> feat: add schemes for event import export

- src/pages/TEIExport/form-helper.js
> fix: tei program status

- src/components/Inputs/FirstRowIsHeader.js
- src/components/Inputs/IsAsync.js
- src/components/Inputs/PreheatCache.js
- src/components/Inputs/SkipAudit.js
- src/components/Inputs/SkipExistingCheck.js
- src/components/Inputs/SkipSharing.js
- src/components/Inputs/SkipValidation.js
- src/components/Inputs/index.js
- src/pages/DataImport/DataImport.js
- src/pages/DataImport/form-helper.js
- src/pages/EventImport/form-helper.js
- src/pages/GMLImport/form-helper.js
- src/pages/MetadataImport/MetadataImport.js
- src/pages/TEIImport/TEIImport.js
- src/utils/helper.js
Addresses:
- DHIS2-9398 (Error when recreating a metadata import job)
- DHIS2-9447 (Async data value import doesn't produce import summaries)
> fix: async/sync summary

- i18n/en.pot
- src/components/Inputs/ImportReportMode.js
- src/components/Inputs/ImportStrategy.js
- src/components/Inputs/Inclusion.js
- src/components/Inputs/InclusionStrategy.js
- src/components/Inputs/MergeMode.js
- src/components/Inputs/OrgUnitMode.js
- src/components/Inputs/Strategy.js
- src/components/RadioGroup/RadioGroup.js
- src/components/RadioGroup/RadioGroup.module.css
Addresses:
- DHIS2-9490 (Difficult to read technical terms prefixing options)
> feat(ui): style prefix technical terms

- src/pages/TEIImport/TEIImport.js
Addresses:
- DHIS2-9523 (Remove async option for TEI import)
> fix(tei-import): remove async option and keep all imports sync

- i18n/en.pot
- src/components/Inputs/AssignedUserMode.js
- src/components/Inputs/AssignedUserModeFilter.js
- src/components/Inputs/index.js
- src/pages/DataExport/form-helper.js
- src/pages/EventExport/form-helper.js
- src/pages/MetadataDependencyExport/form-helper.js
- src/pages/MetadataExport/form-helper.js
- src/pages/TEIExport/TEIExport.js
- src/pages/TEIExport/form-helper.js
> chore(port): pr 704 to v35

- i18n/en.pot
- src/components/Inputs/AssignedUserMode.js
- src/components/Inputs/AssignedUserModeFilter.js
- src/components/Inputs/index.js
- src/pages/DataExport/form-helper.js
- src/pages/EventExport/form-helper.js
- src/pages/MetadataDependencyExport/form-helper.js
- src/pages/MetadataExport/form-helper.js
- src/pages/TEIExport/TEIExport.js
- src/pages/TEIExport/form-helper.js
> chore(port): pr 704 to patch/2.35.0

- cypress/integration/EndpointParamChecks/ImportMetaData.feature
- src/pages/import/MetaData.js
- src/pages/import/MetaData/helper.js
Fixes DHIS2-10532
Option removed from BE; not working
> fix(import metadata): remove preheat mode

- src/components/Inputs/Identifier.js
Fixes DHIS2-10385
([link](https://jira.dhis2.org/browse/DHIS2-10385))
Replaces #1112
> feat(metadata import): remove "AUTO" option, closes DHIS2-10385

- src/components/Inputs/Identifier.js
Backport of #1114
Fixes DHIS2-10385
([link](https://jira.dhis2.org/browse/DHIS2-10385))
Replaces #1113
> feat(metadata import): remove "AUTO" option, closes DHIS2-10385 (v36)

- package.json
- src/components/DatePicker/__snapshots__/DatePicker.test.js.snap
- src/components/JobSummary/__test__/__snapshots__/JobSummary.test.js.snap
- src/components/Page/__snapshots__/Page.test.js.snap
- src/components/RadioGroup/__snapshots__/RadioGroup.test.js.snap
- src/components/Select/__snapshots__/Select.test.js.snap
- src/components/Sidebar/Sidebar.js
- yarn.lock
This PR adds `href`s to the `MenuItem`s in the sidebar, allowing users to ctrl/shift-click them in order to open pages in new tabs.
> feat: add href to MenuItems in sidebar

- i18n/en.pot
- src/App.js
Closes https://jira.dhis2.org/browse/DHIS2-11604
> fix: ensure locales are imported before components

- i18n/en.pot
- src/App.js
v36 backport of https://github.com/dhis2/import-export-app/pull/1168
> fix: ensure locales are imported before components (v36)

- src/App.module.css
Closes https://jira.dhis2.org/browse/DHIS2-11618
> fix: apply text wrapping to navigation bar items

- src/App.module.css
v35 backport of https://github.com/dhis2/import-export-app/pull/1175
> fix: apply text wrapping to navigation bar items (v35)

- src/App.module.css
v36 backport of https://github.com/dhis2/import-export-app/pull/1175
> fix: apply text wrapping to navigation bar items (v36)

- src/App.module.css
> fix: apply text wrapping to navigation bar items (patch/2.35.7)

- package.json
- src/components/DatePicker/__snapshots__/DatePicker.test.js.snap
- src/components/ImportButtonStrip/__snapshots__/ImportButtonStrip.test.js.snap
- src/components/JobSummary/__test__/__snapshots__/JobSummary.test.js.snap
- src/components/Page/__snapshots__/Page.test.js.snap
- src/components/RadioGroup/__snapshots__/RadioGroup.test.js.snap
- src/components/ResourcePicker/ResourcePicker.js
- src/components/Schemas/Schemas.js
- src/components/Select/__snapshots__/Select.test.js.snap
- src/pages/Home/HomeCard.js
- yarn.lock
https://jira.dhis2.org/browse/LIBS-200. Updating to the new app-runtime release.
> chore(deps): update app-runtime to latest

- src/components/Schemas/Schemas.js
Closes DHIS2-12232 ([link](https://jira.dhis2.org/browse/DHIS2-12232))
> fix(schemas component): use "useEffect" instead of "onComplete"

- src/components/Inputs/Format.js
- src/components/Inputs/index.js
- src/pages/DataExport/DataExport.js
- src/pages/DataExport/form-helper.js
- src/utils/helper.js
This PR adds ADX option for data export (see https://jira.dhis2.org/browse/DHIS2-4978)
It is the same as https://github.com/dhis2/import-export-app/pull/1288 by @tomzemp but since that is in an external repo, it seems we can neither run the tests nor merge it.
> fix: add ADX option for data export

- i18n/en.pot
- src/components/JobSummary/SingleSummary/SingleSummary.js
Fixes for 2.39: https://dhis2.atlassian.net/browse/DHIS2-7171?focusedCommentId=175417
2.39 backport of: https://github.com/dhis2/import-export-app/pull/1491/
> fix: avoid app crash when GeoJSON file is invalid (DHIS2-7171, 2.39 backport)

- cypress/integration/EndpointParamChecks/ExportTEI.feature
- cypress/support/form/helpers/nameToDataTest.js
- cypress/support/form/selectFormInput.js
- src/pages/TEIExport/form-helper.js
Backport for https://github.com/dhis2/import-export-app/pull/1546 for `v38`
> fix(tei-export): use correct param name for teiTypeFilter (v38)

- cypress/integration/EndpointParamChecks/ExportTEI.feature
- cypress/support/form/helpers/nameToDataTest.js
- cypress/support/form/selectFormInput.js
- src/pages/TEIExport/form-helper.js
Backport for https://github.com/dhis2/import-export-app/pull/1546 for `v39`
> fix(tei-export): use correct param name for teiTypeFilter (v39)

- cypress/integration/EndpointParamChecks/ExportTEI.feature
- cypress/support/form/helpers/nameToDataTest.js
- cypress/support/form/selectFormInput.js
- src/pages/TEIExport/form-helper.js
Backport for https://github.com/dhis2/import-export-app/pull/1546 for `patch/2.39.0`
> fix(tei-export): use correct param name for teiTypeFilter (patch/2.39.0)

- src/components/ResourcePicker/ResourcePicker.js
Fixes [DHIS2-13971](https://dhis2.atlassian.net/browse/DHIS2-13971) for `patch/2.39.0`
> fix: don't show list when empty [DHIS2-13971] (patch/2.39.0) 

- src/components/ResourcePicker/ResourcePicker.js
Fixes [DHIS2-13971](https://dhis2.atlassian.net/browse/DHIS2-13971)
> fix: don't show list when empty [DHIS2-13971] (master)

- src/components/Inputs/ImportStrategy.js
Backport of https://github.com/dhis2/import-export-app/pull/1655
> fix: metadata update - DHIS2-12479 (v39 backport)

- src/components/Inputs/ImportStrategy.js
Backport of https://github.com/dhis2/import-export-app/pull/1655
> fix: metadata update - DHIS2-12479 (v38 backport)

- src/components/Inputs/ImportStrategy.js
Backport of https://github.com/dhis2/import-export-app/pull/1655
> fix: metadata update - DHIS2-12479 (v37 backport)

- src/components/DatePicker/DatePicker.js
- src/components/DatePicker/DatePicker.test.js
- src/components/DatePicker/DatePickerField.js
- src/pages/DataExport/DataExport.js
- src/pages/DataExport/form-helper.js
- src/pages/EventExport/EventExport.js
- src/pages/EventExport/form-helper.js
- src/pages/TEIExport/form-helper.js
Backport of https://github.com/dhis2/import-export-app/pull/1750
> fix: use string for date inputs [DHIS2-12489] (v40)

- src/components/DatePicker/DatePicker.js
- src/components/DatePicker/DatePicker.test.js
- src/components/DatePicker/DatePickerField.js
- src/pages/DataExport/DataExport.js
- src/pages/DataExport/form-helper.js
- src/pages/EventExport/EventExport.js
- src/pages/EventExport/form-helper.js
- src/pages/TEIExport/form-helper.js
Backport for https://github.com/dhis2/import-export-app/pull/1750
> fix: use string for date inputs [DHIS2-12489] (v39)

- src/components/DatePicker/DatePicker.js
- src/components/DatePicker/DatePicker.test.js
- src/components/DatePicker/DatePickerField.js
- src/pages/DataExport/DataExport.js
- src/pages/DataExport/form-helper.js
- src/pages/EventExport/EventExport.js
- src/pages/EventExport/form-helper.js
- src/pages/TEIExport/form-helper.js
Backport of https://github.com/dhis2/import-export-app/pull/1750
> fix: use string for date inputs [DHIS2-12489] (v38)

- src/components/ElementSchemes/DataElementIdScheme.js
- src/components/ElementSchemes/OrgUnitIdScheme.js
- src/components/MoreOptions/MoreOptions.js
- src/components/MoreOptions/MoreOptions.module.css
- src/components/MoreOptions/__snapshots__/MoreOptions.test.js.snap
- src/components/Page/__snapshots__/Page.test.js.snap
> fix: avoid breaking selects (v38) [DHIS2-16264] (#1963)

- src/components/ElementSchemes/DataElementIdScheme.js
- src/components/ElementSchemes/OrgUnitIdScheme.js
- src/components/MoreOptions/MoreOptions.js
- src/components/MoreOptions/MoreOptions.module.css
- src/components/MoreOptions/__snapshots__/MoreOptions.test.js.snap
- src/components/Page/__snapshots__/Page.test.js.snap
> fix: avoid breaking selects (v40) [DHIS2-16264] (#1963)

- package.json
BREAKING CHANGE: this is for continuous release (missed adding a tag last time)
> fix: update version number for app

- src/components/ResourcePicker/queries.js
Implements [DHIS2-16015](https://dhis2.atlassian.net/browse/DHIS2-16015)
---
added a filter to get programs by program type of with registration.
---
-   [ ] None
---
[DHIS2-16015]: https://dhis2.atlassian.net/browse/DHIS2-16015?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: update the query to filter programs by program type

- src/components/ResourcePicker/ResourcePicker.js
Fixes [DHIS2-13971](https://dhis2.atlassian.net/browse/DHIS2-13971) for `v39`
> fix: don't show list when empty [DHIS2-13971] (v39)

- src/components/Inputs/ProgramPicker.js
- src/components/Inputs/__tests__/ProgramPicker.test.js
- src/components/ResourcePicker/ResourcePicker.js
- src/components/ResourcePicker/queries.js
- src/components/ResourcePicker/resourceTypes.js
- src/pages/EventExport/EventExport.js
v40 backport of https://github.com/dhis2/import-export-app/pull/2058
tested against debug.dhis2.org/2.40dev
> fix: include event programs for export [DHIS2-17672] (v40)
